### ISSUE TITLE
Debugger not accessible within module.export

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/node-debugger-lab#3]
Lab ships with line one:

```
module.exports = function() {
  var output = {}
  var customerAccount = {
...
```

this is for testing purposes. When you run `node debug account.js` it skips all the code. A note in the readme to comment out line one ( `module.exports = function() {`), and the last curly bracket when debugging will save students time.

A cleaner alternative would be to simply define the function outside the export.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by onyoo** [comment]
To reproduce, open the lesson and run `node debug account.js`. You will see that the code never available to debug.

To fix, comment-out the first line and last`}` on account.js.

**Comment by pletcher** [comment]
Hi @onyoo, I'm not able to reproduce this issue. If I add a `debugger` statement to the first line inside in the main function -- so it looks like

``` javascript
module.exports = function() {
  debugger
  var output = {}
  // etc.
}
```

I get the following:

<img width="682" alt="screen shot 2016-07-25 at 10 00 18 am" src="https://cloud.githubusercontent.com/assets/2015049/17103916/98e3074e-524e-11e6-9404-4843dd05b100.png">

Are you adding `debugger` statements? The `debug` in `node debug account.js` will be a no-op without those :)

**Comment by onyoo** [comment]
Hi @pletcher, yes I should have been more specific. If you enter `n` or `s` to go to the next line, or step-in as the lab requests, it skips the block of code to be debugged. Let me know results differ.

**Comment by pletcher** [comment]
I see, that makes sense. Nothing is actually getting executed -- when you remove the `module.exports = function() {` declaration (and the closing `}`), the script is evaluated when run with `node debug`, so the breakpoints you've set get hit; without that, as you've noticed, there's nothing really to break on.

I'll update the instructions -- the simplest thing will be to name the exported function and call it at the bottom of the file (then you can remove the call for tests to pass).
